---
name: "Lint Rust"

on:  # yamllint disable-line rule:truthy
  - pull_request
  - push

jobs:
  lint_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: "stable"
      - name: "Lint Rust"
        run: "cargo fmt --all -- --check"
...
